# Generated by Django 3.2.9 on 2021-12-28 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 18, 28, 4, 857871)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_body', models.TextField()),
                ('comment_date', models.DateField(default=datetime.date.today)),
                ('fk_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.item')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user')),
            ],
        ),
    ]
