# Generated by Django 3.2.9 on 2021-12-28 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20211228_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 28, 19, 59, 20, 61750)),
        ),
        migrations.CreateModel(
            name='User_Images',
            fields=[
                ('user_img_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_img_name', models.ImageField(upload_to='User_Image')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.user')),
            ],
        ),
    ]
